export type Team = {
  name: string;
  short: string;
  slug: string;
  logo: string | null;
  form: string;
  seasons: number[];
};

export const teams: Team[] = [
  {
    name: "Milton Town FC",
    short: "MTF",
    slug: "milton-town-fc",
    logo: "/MILTOWN TOWN FC.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Newham United",
    short: "NEW",
    slug: "newham-united",
    logo: "/NEWHAM UNITED.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Nottingham Rangers",
    short: "NTR",
    slug: "nottingham-rangers",
    logo: "/Nottingam Rangers FC.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Canterbury FC",
    short: "CFC",
    slug: "canterbury-fc",
    logo: "/canterbury FC.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Andover FC",
    short: "AFC",
    slug: "andover-fc",
    logo: "/Andover FC.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Eltham United",
    short: "ELT",
    slug: "eltham-united",
    logo: "/ELTHAM UNITED.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Newport Wanderers FC",
    short: "NPW",
    slug: "newport-wanderers-fc",
    logo: "/Newport Wanderers FC.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Stanford FC",
    short: "STF",
    slug: "stanford-fc",
    logo: "/Stanford FC.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Deportivo Di Gnoa",
    short: "DDG",
    slug: "deportivo-di-gnoa",
    logo: "/Deportivo Di Gnoa.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "AC Casole",
    short: "ACC",
    slug: "ac-casole",
    logo: "/AC Casole.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Tre Torre Libertas FC",
    short: "TTL",
    slug: "tre-torre-libertas-fc",
    logo: "/Tre Torre Libertas FC.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Venezia A.C.",
    short: "VEN",
    slug: "venezia-ac",
    logo: "/Venezia A.C..png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Cartigiana FC",
    short: "CAR",
    slug: "cartigiana-fc",
    logo: "/Cartigiana FC.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Viola FC",
    short: "VIO",
    slug: "viola-fc",
    logo: "/Viola FC.png",
    form: "League squad",
    seasons: [1, 2],
  },
  {
    name: "Sassari Calcio",
    short: "SAS",
    slug: "sassari-calcio",
    logo: "/Sassari Calcio.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Ambasciatori Milano",
    short: "AMB",
    slug: "ambasciatori-milano",
    logo: "/Ambasciatori Milano.png",
    form: "League squad",
    seasons: [2],
  },
  {
    name: "Stafford Wanderers",
    short: "STW",
    slug: "stafford-wanderers",
    logo: "/Stafford Wanderers.png",
    form: "League squad",
    seasons: [1],
  },

  // --- Season 3 · National teams (international / World Cup roster) ---
  {
    name: "France",
    short: "FRA",
    slug: "france",
    logo: "/France.png",
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Spain",
    short: "ESP",
    slug: "spain",
    logo: "/Spain.png",
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "England",
    short: "ENG",
    slug: "england",
    logo: "/England.png",
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Germany",
    short: "GER",
    slug: "germany",
    logo: "/Germany.png",
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Belgium",
    short: "BEL",
    slug: "belgium",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Croatia",
    short: "CRO",
    slug: "croatia",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Netherlands",
    short: "NED",
    slug: "netherlands",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Italy",
    short: "ITA",
    slug: "italy",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Portugal",
    short: "POR",
    slug: "portugal",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Türkiye",
    short: "TUR",
    slug: "turkiye",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Brazil",
    short: "BRA",
    slug: "brazil",
    logo: null,
    form: "National squad · Season 3 · Hosts",
    seasons: [3],
  },
  {
    name: "Argentina",
    short: "ARG",
    slug: "argentina",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Colombia",
    short: "COL",
    slug: "colombia",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Uruguay",
    short: "URU",
    slug: "uruguay",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Ecuador",
    short: "ECU",
    slug: "ecuador",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "USA",
    short: "USA",
    slug: "usa",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Canada",
    short: "CAN",
    slug: "canada",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Mexico",
    short: "MEX",
    slug: "mexico",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Algeria",
    short: "ALG",
    slug: "algeria",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Nigeria",
    short: "NGA",
    slug: "nigeria",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Morocco",
    short: "MAR",
    slug: "morocco",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "South Africa",
    short: "RSA",
    slug: "south-africa",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "Japan",
    short: "JPN",
    slug: "japan",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
  {
    name: "South Korea",
    short: "KOR",
    slug: "south-korea",
    logo: null,
    form: "National squad · Season 3",
    seasons: [3],
  },
];

export function getTeamBySlug(slug: string): Team | undefined {
  return teams.find((team) => team.slug === slug);
}
